apiVersion: v1
kind: Pod
metadata:
  labels:
    component: haproxy
  name: haproxy
  namespace: kube-system
spec:
  containers:
  - command:
    - haproxy
    - -f
    - /etc/haproxy/haproxy.cfg
    image: haproxy:2.9-alpine
    imagePullPolicy: IfNotPresent
    name: haproxy
    resources:
      requests:
        cpu: 50m
    volumeMounts:
    - mountPath: /etc/haproxy
      name: haproxy
  - command:
    - hacox
    - --haproxy-config=/etc/haproxy/haproxy.cfg
    - --servers-config=/etc/haproxy/backend-servers.yaml
    - --kube-config=/etc/kubernetes/kubelet.conf
    - --server-port=6443
    - --refresh-interval=1m
    image: ghcr.io/klusterdock/hacox:latest
    imagePullPolicy: IfNotPresent
    name: hacox
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    resources:
      requests:
        cpu: 50m
      limit:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/kubelet.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /var/lib/kubelet/pki
      name: kubelet-pki
      readOnly: true
    - mountPath: /etc/haproxy
      name: haproxy
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  shareProcessNamespace: true
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/kubelet.conf
      type: ""
    name: kubeconfig
  - hostPath:
      path: /var/lib/kubelet/pki
      type: DirectoryOrCreate
    name: kubelet-pki
  - hostPath:
      path: /etc/kubernetes/haproxy
      type: DirectoryOrCreate
    name: haproxy
status: {}